<a href="https://colab.research.google.com/github/wonjae11/AI_TEST/blob/main/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01. 텐서 초기화
- 초기화 : 텐서에서 특정 값을 채워서 생성하는 것

In [2]:
import torch
import numpy as np

### 1-1. 초기화 되지 않은 텐서
- 특정한 값이 채워지지 않은 상태로 생성하는 것

In [ ]:
tensor = torch.empty(4,2)
print(tensor)

tensor([[7.0062e+22, 2.1715e-18],
        [4.5447e+30, 7.0062e+22],
        [2.1707e-18, 1.9284e+31],
        [3.2314e-18, 9.6635e-06]])


### 1-2. 상수로 초기화된 텐서
- 'torch.zeros()'
- 'torch.ones()'

In [ ]:
a = torch.ones(3,4, dtype=torch.long) # dtype= 데이터타입 지정
b = torch.zeros(2,2)
print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0., 0.],
        [0., 0.]])


### 1-3. 무작위로 초기화된 텐서
- 'torch.rand()' : 0~1사이의 값으로 무작위로 초기화
- 'torch.randn()' : 표준정규분포에서 무작위로 초기화

In [ ]:
a = torch.rand(3,3)
b = torch.randn(3,3)
b

tensor([[ 0.0086, -0.4802,  0.6112],
        [-0.3770,  0.8562,  0.2378],
        [-0.5292,  1.1741, -2.5302]])

### 1-4. 직접 입력한 값으로 초기화


In [ ]:
a = torch.tensor([1,2.3])
a

tensor([1.0000, 2.3000])

### 1-5. Numpy 배열로부터 초기화

In [ ]:
nd_arr = np.array([1,2,3])
a = torch.from_numpy(nd_arr)

b = torch.tensor([1,2.3])
new_nd = b.numpy()
type(new_nd)

numpy.ndarray

### 1-6. 특정 텐서와 같은 사이즈, 무작위로 값을 채움

In [ ]:
a = torch.ones(3,4, dtype=torch.long)
b = torch.zeros_like(a, dtype=torch.float)
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 1-7. 텐서의 속성

In [7]:
tensor = torch.rand(3,4, dtype=torch.float64)
print(tensor.size())
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.Size([3, 4])
torch.float64
cpu


### 1-8. 특정 타입의 텐서 생성

In [9]:
tensor = torch.rand(3,4,dtype=torch.float64)
tensor.dtype

float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor)

int_tensor = torch.IntTensor([1.1,2.3,3.4])
print(int_tensor)
print(int_tensor.dtype)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
torch.int32


### 1-9. 데이터 타입 캐스팅

In [10]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())

int_tensor = torch.IntTensor([1,2,3])
print(int_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


### 1-10. CUDA 텐서

In [12]:
a = torch.ones(3,4, dtype=torch.long)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
tensor.device

device(type='cuda', index=0)

### 1-11. 다차원 텐서

#### 1-11-1. 0D Tensor(Scalar)
- 하나의 값을 담고 있는 텐서



In [15]:
t0 = torch.tensor(100)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(100)


#### 1-11-2. 1D Tensor(Vector)
- 값들을 저장하고 있는 리스트와 유사한 텐서

In [16]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


#### 1-11-3. 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두개의 축이 존재

In [17]:
t2 = torch.tensor([[1,2,3],[4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


#### 1-11-4. 3D Tensor(Cube)
- 큐브와 같은 형태로 세 개의 축이 존재

In [19]:
t3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                  [[1,2,3],[4,5,6],[7,8,9]],
                  [[1,2,3],[4,5,6],[7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


#### 1-11-5. 4D Tensor
- 4개의 축

In [21]:
t4 = torch.rand(3,2,3,2)

print(t4.ndim)
print(t4.shape)
print(t4)

4
torch.Size([3, 2, 3, 2])
tensor([[[[0.2736, 0.1730],
          [0.6988, 0.2174],
          [0.5597, 0.0534]],

         [[0.2217, 0.4346],
          [0.2174, 0.5726],
          [0.9196, 0.6357]]],


        [[[0.2325, 0.8658],
          [0.0920, 0.1589],
          [0.9807, 0.3950]],

         [[0.3178, 0.5047],
          [0.5269, 0.7902],
          [0.2728, 0.3476]]],


        [[[0.4989, 0.3480],
          [0.8484, 0.2056],
          [0.9261, 0.2715]],

         [[0.9645, 0.9006],
          [0.0390, 0.9710],
          [0.8960, 0.2127]]]])
