<a href="https://colab.research.google.com/github/wonjae11/AI_TEST/blob/main/03_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 03. 텐서의 조작

In [ ]:
import torch

### 3-1. 인덱싱, 슬라이싱
- numpy처럼 활용

In [ ]:
tensor = torch.tensor([[1,2],[3,4]])
print(tensor[0,1])
print(tensor[0,:])

a = torch.tensor([1,2,3,4,5])
print(a[-2:])

b = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
c = b[b>5]
d = b[b % 2 == 0]
e = b[[0,1],[1,2]]
e

tensor(2)
tensor([1, 2])
tensor([4, 5])


tensor([2, 6])

### 3-2. 텐서의 크기, 모양 변경

In [ ]:
t = torch.rand(4,5)
print(t)
x = t.view(5,4)
print(x)
y = t.view(10,-1)
print(y)

tensor([[0.8792, 0.3592, 0.8217, 0.4680, 0.1675],
        [0.4226, 0.1241, 0.0751, 0.7895, 0.3625],
        [0.4767, 0.3706, 0.4019, 0.3689, 0.7140],
        [0.1412, 0.1116, 0.4050, 0.5492, 0.2184]])
tensor([[0.8792, 0.3592, 0.8217, 0.4680],
        [0.1675, 0.4226, 0.1241, 0.0751],
        [0.7895, 0.3625, 0.4767, 0.3706],
        [0.4019, 0.3689, 0.7140, 0.1412],
        [0.1116, 0.4050, 0.5492, 0.2184]])
tensor([[0.8792, 0.3592],
        [0.8217, 0.4680],
        [0.1675, 0.4226],
        [0.1241, 0.0751],
        [0.7895, 0.3625],
        [0.4767, 0.3706],
        [0.4019, 0.3689],
        [0.7140, 0.1412],
        [0.1116, 0.4050],
        [0.5492, 0.2184]])


### 3-3. 텐서의 숫자값 얻기

In [ ]:
x = torch.tensor(10)
print(x.item())

y = torch.rand(1)
print(y)
print(y.item())

10
tensor([0.6387])
0.6386762857437134


### 3-4. 차원 축소와 증가


#### 3-4-1. 차원 축소(삭제)
- 'torch.squeeze()' : 크기가 1인 차원을 축소함

In [ ]:
t = torch.rand(1,3,3)
print(t.shape)

ts = torch.squeeze(t)

print(ts.shape)

torch.Size([1, 3, 3])
torch.Size([3, 3])


#### 3-4-2. 차원 증가(생성)
- torch.unsqueeze() : 지정한 위치에 새로운 차원 생성

In [ ]:
t = torch.rand(3,3,3)
print(t)
print(t.shape)

ts = torch.unsqueeze(t,2)
print(ts)
print(ts.shape)

tensor([[[0.5884, 0.8609, 0.3083],
         [0.5583, 0.6524, 0.8748],
         [0.6835, 0.1149, 0.7219]],

        [[0.1893, 0.0398, 0.6459],
         [0.5148, 0.2315, 0.0292],
         [0.0642, 0.7666, 0.6585]],

        [[0.6010, 0.6426, 0.9368],
         [0.8182, 0.7840, 0.7700],
         [0.4767, 0.0456, 0.6800]]])
torch.Size([3, 3, 3])
tensor([[[[0.5884, 0.8609, 0.3083]],

         [[0.5583, 0.6524, 0.8748]],

         [[0.6835, 0.1149, 0.7219]]],


        [[[0.1893, 0.0398, 0.6459]],

         [[0.5148, 0.2315, 0.0292]],

         [[0.0642, 0.7666, 0.6585]]],


        [[[0.6010, 0.6426, 0.9368]],

         [[0.8182, 0.7840, 0.7700]],

         [[0.4767, 0.0456, 0.6800]]]])
torch.Size([3, 3, 1, 3])


### 3-5. 텐서간 결합

- torch.stack() : 동일한 형식의 텐서를 새롭게 그룹화 함

In [ ]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])
z = torch.stack([x,y])
print(z)
print(z.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


- torch.cat() : 하나의 텐서로 병합
  - 새로운 차원 생성 X

In [ ]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])
z = torch.stack([x,y], dim=1)
print(z)

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


### 3-8. 텐서 나누기

- torch.chunk():
  - 텐서를 몇개로 나눌지 지정
  - 나누어 떨어지지 않으면 마지막 조각은 크기 다를 수 있음

In [ ]:
t = torch.rand(5,3)
print(t)

a,b,c = torch.chunk(t,3,dim=0)
print(a,b,c)

tensor([[0.3983, 0.7039, 0.1805],
        [0.6355, 0.2210, 0.8071],
        [0.6719, 0.6615, 0.1890],
        [0.0873, 0.0945, 0.2303],
        [0.4693, 0.7071, 0.4894]])
tensor([[0.3983, 0.7039, 0.1805],
        [0.6355, 0.2210, 0.8071]]) tensor([[0.6719, 0.6615, 0.1890],
        [0.0873, 0.0945, 0.2303]]) tensor([[0.4693, 0.7071, 0.4894]])


- torch.split()
  - 텐서의 크기를 기준으로 나눔

In [ ]:
t = torch.rand(3,6)
print(t)

x = torch.split(t,3,dim=1)
print(x)

tensor([[0.8993, 0.4029, 0.8680, 0.1593, 0.7361, 0.2660],
        [0.0808, 0.1754, 0.4686, 0.2308, 0.5309, 0.8751],
        [0.4405, 0.1239, 0.4436, 0.1495, 0.5999, 0.3685]])
(tensor([[0.8993, 0.4029, 0.8680],
        [0.0808, 0.1754, 0.4686],
        [0.4405, 0.1239, 0.4436]]), tensor([[0.1593, 0.7361, 0.2660],
        [0.2308, 0.5309, 0.8751],
        [0.1495, 0.5999, 0.3685]]))


In [ ]:
t = torch.tensor([1,2,3,4,5])
print(t)

x,y,z = torch.split(t,[2,2,1],dim=0)
print(x)
print(y)
print(z)

tensor([1, 2, 3, 4, 5])
tensor([1, 2])
tensor([3, 4])
tensor([5])
