<a href="https://colab.research.google.com/github/wonjae11/AI_TEST/blob/main/quiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Quiz 1 : Tensor 초기화

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [ ]:
import torch
import numpy as np

x = torch.empty(3,4)
x

tensor([[1.5336e-36, 4.4553e-41, 1.5338e-36, 4.4553e-41],
        [1.5338e-36, 4.4553e-41, 1.5338e-36, 4.4553e-41],
        [1.5338e-36, 4.4553e-41, 1.5338e-36, 4.4553e-41]])

### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [ ]:
x = torch.zeros(2,5,3,dtype=torch.float64)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [ ]:
x = torch.ones(4,4,dtype=torch.int)
x

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [ ]:
x = torch.rand(3,3)
x

tensor([[0.7430, 0.0721, 0.1890],
        [0.1919, 0.0231, 0.1124],
        [0.7780, 0.4366, 0.8662]])

### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [11]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 값을 모두 0으로 바꿔보세요.

In [8]:
x = torch.randn(2,2)
y = torch.zeros_like(x)
y

tensor([[0., 0.],
        [0., 0.]])